name: Docker

on:
  push:
    branches:
      - main
      - develop

env:
  REGISTRY: docker.io
  REPOSITORY: shadynitesh/gratitudefrontend
  IMAGE_NAME: gratitudefrontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.11.0'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_NAME }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=maxForthis

      - name: Create pull request and release tag
        if: github.ref == 'refs/heads/develop' && success()
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main
          title: Automatic merge of develop into main
          commit-message: Automatic merge of develop into main
          labels: automerge
          body: |
            This pull request is automatically generated by a GitHub Actions workflow.
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create release
        if: github.ref == 'refs/heads/develop' && success()
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.meta.outputs.tags }}
          release_name: Release ${{ steps.meta.outputs.tags }}
          body: |
            Release ${{ steps.meta.outputs.tags }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
 
